name: Update Partners JSON

on:
  #schedule:
  #  - cron: '0 0 * * 1' # Tous les jours à minuit UTC
  workflow_dispatch: # Déclenchement manuel

permissions:
  contents: write # Autoriser les actions à pousser des changements

jobs:
  update-partners:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch partners data
      run: |
        curl -s https://app.hackintheshell.org/api/partners/get_all -o partners.json
        cat partners.json

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add partners.json
        git commit -m "Update partners.json"
        git push
